In [1]:
from sklearn import datasets
from sklearn import svm
from sklearn.model_selection import train_test_split
import numpy as np

In [5]:
digit = datasets.load_digits()
x_train, x_test, y_train, y_test = train_test_split(digit.data, digit.target, train_size=0.6, random_state=42)

In [6]:
y_train.shape

(1078,)

In [ ]:
s = svm.SVC(gamma=0.001)
s.fit(x_train, y_train)

res = s.predict(x_test) # 예측값

In [12]:
len(res)

719

In [ ]:
# 혼동 행렬 구함
conf = np.zeros((10, 10))

for i in range(len(res)):
  conf[res[i]][y_test[i]] += 1 # 예측값이 행, 실제값이 열
  
print(conf)

[[67.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 72.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 66.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 69.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0. 78.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0. 83.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 69.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 70.  0.  1.]
 [ 0.  0.  0.  1.  0.  0.  0.  0. 65.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0. 75.]]


부류 3에 속하는 71개 샘플 중 69개를 3, 1개를 5, 1개를 8로 인식

In [15]:
from sklearn.model_selection import cross_val_score

In [17]:
digit = datasets.load_digits()
s= svm.SVC(gamma=0.001)
accuracy = cross_val_score(s, digit.data, digit.target, cv=5) # 5겹 교차검증

print(accuracy) # 5개의 정확도
print(accuracy.mean()) # 평균 정확도
print(accuracy.std()) # 표준편차

[0.975      0.95       0.98328691 0.99164345 0.96100279]
0.9721866295264624
0.015013488295959767
