In [1]:
import numpy as np

In [21]:
class Embedding:
    def __init__(self, W):
        self.params = [W]  # 가중치 W를 인스턴스 변수 params에 리스트로 저장
        self.grads = [np.zeros_like(W)]  # W와 형상이 같은 행렬을 하나 준비, 0으로 초기화
        self.idx = None

    def forward(self, idx):
        W, = self.params
        self.idx = idx
        out = W[idx]  # W의 idx번째 행을 추출
        return out

    def backward(self, dout):
        dW, = self.grads
        dW[...] = 0  # 기울기 초기화
        np.add.at(dW, self.idx, dout)  # 기울기 계산 및 업데이트
        return None
      
# 랜덤시드 고정
np.random.seed(0)

# 예시 데이터
vocab_size = 10  # 어휘 크기
embed_size = 5    # 임베딩 벡터의 차원
W = np.random.randn(vocab_size, embed_size)  # 임베딩 행렬
print("초기 임베딩 행렬:\n", W)

# Embedding 계층 생성
embedding = Embedding(W)

# 입력 단어 인덱스
idx = np.array([1, 3, 5, 7])

# 순전파
out = embedding.forward(idx)
print("임베딩 벡터 (순전파 결과):\n", out)

# 역전파
dout = np.random.randn(len(idx), embed_size)  # 임의의 기울기
embedding.backward(dout)
print("임베딩 행렬의 기울기 (역전파 결과):\n", embedding.grads[0])

# 파라미터 업데이트 (예: 경사 하강법)
learning_rate = 0.01
W -= learning_rate * embedding.grads[0]
print("업데이트된 임베딩 행렬:\n", W)

new_embedding = Embedding(W)
out = new_embedding.forward(idx)
print("업데이트된 임베딩 벡터 (순전파 결과):\n", out)

초기 임베딩 행렬:
 [[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799]
 [-0.97727788  0.95008842 -0.15135721 -0.10321885  0.4105985 ]
 [ 0.14404357  1.45427351  0.76103773  0.12167502  0.44386323]
 [ 0.33367433  1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362  -0.74216502  2.26975462]
 [-1.45436567  0.04575852 -0.18718385  1.53277921  1.46935877]
 [ 0.15494743  0.37816252 -0.88778575 -1.98079647 -0.34791215]
 [ 0.15634897  1.23029068  1.20237985 -0.38732682 -0.30230275]
 [-1.04855297 -1.42001794 -1.70627019  1.9507754  -0.50965218]
 [-0.4380743  -1.25279536  0.77749036 -1.61389785 -0.21274028]]
임베딩 벡터 (순전파 결과):
 [[-0.97727788  0.95008842 -0.15135721 -0.10321885  0.4105985 ]
 [ 0.33367433  1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-1.45436567  0.04575852 -0.18718385  1.53277921  1.46935877]
 [ 0.15634897  1.23029068  1.20237985 -0.38732682 -0.30230275]]
임베딩 행렬의 기울기 (역전파 결과):
 [[ 0.          0.          0.          0.          0.        ]


In [14]:
out = embedding.forward(idx)

In [15]:
print("임베딩 벡터:\n", out)

임베딩 벡터:
 [[ 0.68729358  2.04845691 -0.46155895  0.68784742  1.00812262 -0.15650898
   0.90007753  1.00047132  0.68837496 -1.88109576]
 [-1.14021442  0.28461596 -0.5422414   0.46351946 -0.86168806  0.87454227
  -0.54425854  0.36996606 -0.43494123  1.11012305]
 [-2.00098553 -1.34775846 -0.22062815 -0.07896638 -0.60784722 -1.24573388
   1.62979432  0.17752857 -0.67198658  0.33112814]
 [ 1.70034868 -0.44126724  0.3144938   0.63629759  0.08677138 -0.11779163
  -1.27587343  0.90675596  0.00606262 -0.85210364]
 [-1.36136676 -0.13551368 -0.5520222  -0.04952922  0.88730775  1.15464672
   0.11576695 -1.16152033 -0.18463154  0.46698407]
 [-1.03764318  0.59365816  1.10268062 -0.51217773 -0.26541986 -1.61700601
  -0.27151449  0.94555425 -0.62699279 -0.26594728]
 [ 0.85995815  0.92045268  0.27060325  0.02781914 -2.18725761  0.13474378
  -0.68145565 -2.42239106  0.42117375 -0.67733465]]
