In [2]:
import numpy as np

In [11]:
np.random.seed(3)

T, H = 5, 4 # T: 시계열의 길이, H: 은닉 상태의 차원 수
hs = np.random.randn(T, H)
print(hs)
a = np.array([0.8, 0.1, 0.03, 0.05, 0.02]) # 가중치

ar = a.reshape(5, 1).repeat(4, axis=1)
print(ar.shape)

t = hs * ar
print(t.shape)
print(t)

c = np.sum(t, axis=0)
print(c) # 맥락 벡터

[[ 1.78862847  0.43650985  0.09649747 -1.8634927 ]
 [-0.2773882  -0.35475898 -0.08274148 -0.62700068]
 [-0.04381817 -0.47721803 -1.31386475  0.88462238]
 [ 0.88131804  1.70957306  0.05003364 -0.40467741]
 [-0.54535995 -1.54647732  0.98236743 -1.10106763]]
(5, 4)
(5, 4)
[[ 1.43090278e+00  3.49207880e-01  7.71979745e-02 -1.49079416e+00]
 [-2.77388203e-02 -3.54758979e-02 -8.27414815e-03 -6.27000677e-02]
 [-1.31454507e-03 -1.43165409e-02 -3.94159426e-02  2.65386714e-02]
 [ 4.40659021e-02  8.54786532e-02  2.50168211e-03 -2.02338707e-02]
 [-1.09071990e-02 -3.09295463e-02  1.96473487e-02 -2.20213526e-02]]
[ 1.43500812  0.35396455  0.05165691 -1.56921078]
