In [2]:
import numpy as np

In [11]:
np.random.seed(3)

T, H = 5, 4 # T: 시계열의 길이, H: 은닉 상태의 차원 수
hs = np.random.randn(T, H)
print(hs)
a = np.array([0.8, 0.1, 0.03, 0.05, 0.02]) # 가중치

ar = a.reshape(5, 1).repeat(4, axis=1)
print(ar.shape)

t = hs * ar
print(t.shape)
print(t)

c = np.sum(t, axis=0)
print(c) # 맥락 벡터

[[ 1.78862847  0.43650985  0.09649747 -1.8634927 ]
 [-0.2773882  -0.35475898 -0.08274148 -0.62700068]
 [-0.04381817 -0.47721803 -1.31386475  0.88462238]
 [ 0.88131804  1.70957306  0.05003364 -0.40467741]
 [-0.54535995 -1.54647732  0.98236743 -1.10106763]]
(5, 4)
(5, 4)
[[ 1.43090278e+00  3.49207880e-01  7.71979745e-02 -1.49079416e+00]
 [-2.77388203e-02 -3.54758979e-02 -8.27414815e-03 -6.27000677e-02]
 [-1.31454507e-03 -1.43165409e-02 -3.94159426e-02  2.65386714e-02]
 [ 4.40659021e-02  8.54786532e-02  2.50168211e-03 -2.02338707e-02]
 [-1.09071990e-02 -3.09295463e-02  1.96473487e-02 -2.20213526e-02]]
[ 1.43500812  0.35396455  0.05165691 -1.56921078]


In [12]:
# 미니배치 버전
N, T, H = 10, 5, 4
hs = np.random.randn(N, T, H) # 미니배치 수: N , 시계열의 길이: T, 은닉 상태의 차원 수: H -> 하나의 미니배치에 10개의 시계열 데이터가 있고 이 시계열 데이터의 길이는 5이며, 각 시계열 데이터의 은닉 상태의 차원 수는 4이다.
print(hs)
a = np.random.randn(N, T)
ar = a.reshape(N, T, 1).repeat(H, axis=2)
print(ar.shape)

[[[-1.18504653e+00 -2.05649899e-01  1.48614836e+00  2.36716267e-01]
  [-1.02378514e+00 -7.12993200e-01  6.25244966e-01 -1.60513363e-01]
  [-7.68836350e-01 -2.30030722e-01  7.45056266e-01  1.97611078e+00]
  [-1.24412333e+00 -6.26416911e-01 -8.03766095e-01 -2.41908317e+00]
  [-9.23792022e-01 -1.02387576e+00  1.12397796e+00 -1.31914233e-01]]

 [[-1.62328545e+00  6.46675452e-01 -3.56270759e-01 -1.74314104e+00]
  [-5.96649642e-01 -5.88594380e-01 -8.73882298e-01  2.97138154e-02]
  [-2.24825777e+00 -2.67761865e-01  1.01318344e+00  8.52797841e-01]
  [ 1.10818750e+00  1.11939066e+00  1.48754313e+00 -1.11830068e+00]
  [ 8.45833407e-01 -1.86088953e+00 -6.02885104e-01 -1.91447204e+00]]

 [[ 1.04814751e+00  1.33373782e+00 -1.97414679e-01  1.77464503e+00]
  [-6.74727510e-01  1.50616865e-01  1.52945703e-01 -1.06419527e+00]
  [ 4.37946611e-01  1.93897846e+00 -1.02493087e+00  8.99338446e-01]
  [-1.54506852e-01  1.76962730e+00  4.83788348e-01  6.76216400e-01]
  [ 6.43163281e-01  2.49086707e-01 -1.395763